SCAM_TYPES = [
    {
        "slug": "phishing",
        "title": "Phishing Scams",
        "icon": "Fish",
        "severity": "critical",
        "description": "Phishing is a cyber attack where scammers impersonate trusted organizations (banks, government, popular websites) via email, SMS, or fake websites to steal your passwords, card numbers, and personal data.",
        "how_it_works": "You receive an urgent email or SMS that looks official — 'Your account will be suspended', 'Verify your KYC', or 'You have a pending refund'. The message contains a link to a fake website that looks identical to the real one. When you enter your login credentials or card details, they go straight to the scammer.",
        "warning_signs": ["Urgent language demanding immediate action", "Sender email address is slightly misspelled (e.g., support@paypa1.com)", "Links that don't match the official domain", "Generic greetings like 'Dear Customer'", "Requests for passwords, OTPs, or card details"],
        "prevention_tips": ["Never click links in unsolicited emails or SMS", "Type the official website URL manually in your browser", "Check for HTTPS and the exact domain spelling", "Enable two-factor authentication everywhere", "Report phishing emails to your provider"],
        "real_example": "In 2024, thousands of users received emails claiming to be from their bank asking them to 'update KYC within 24 hours'. The link led to a pixel-perfect clone of the bank's site. Victims who entered their credentials lost an average of $1,800 each before banks flagged the fraud."
    },
    {
        "slug": "otp-fraud",
        "title": "OTP Fraud",
        "icon": "KeyRound",
        "severity": "critical",
        "description": "OTP (One-Time Password) fraud happens when scammers trick you into sharing the OTP sent to your phone, giving them access to your bank account, UPI, or online accounts.",
        "how_it_works": "A scammer calls pretending to be from your bank, a delivery company, or customer support. They claim they need the OTP 'to verify your identity', 'cancel a transaction', or 'process a refund'. The moment you share it, they complete a transaction or take over your account.",
        "warning_signs": ["Anyone asking you to share an OTP over phone or chat", "Calls claiming a transaction 'happened by mistake'", "Pressure to act quickly before the OTP expires", "Caller already knows some of your personal details", "Requests to install screen-sharing apps"],
        "prevention_tips": ["NEVER share an OTP with anyone — banks never ask for it", "Read the full OTP SMS: it tells you what the OTP authorizes", "Hang up and call the official customer care number yourself", "Never install remote access apps like AnyDesk for 'support'", "Block and report suspicious numbers"],
        "real_example": "A retired teacher received a call from a 'bank executive' saying his debit card would be blocked unless he verified an OTP. He shared 3 OTPs over 10 minutes. Each one authorized a transfer — he lost his entire savings of $12,000 in under 15 minutes."
    },
    {
        "slug": "upi-payment-scams",
        "title": "UPI Payment Scams",
        "icon": "Smartphone",
        "severity": "critical",
        "description": "UPI scams exploit instant payment apps (Google Pay, PhonePe, Paytm) using fake payment requests, QR codes, and 'cashback' tricks to drain your account in seconds.",
        "how_it_works": "Scammers send a 'collect request' disguised as an incoming payment, or share a QR code claiming you'll RECEIVE money by scanning it. In reality, scanning a QR or approving a collect request with your PIN SENDS money. Fake 'customer support' numbers found on Google also direct victims to make 'verification payments'.",
        "warning_signs": ["Someone says you must enter your UPI PIN to RECEIVE money", "QR codes sent to you for 'receiving' payments", "Collect requests from unknown IDs", "Sellers/buyers on marketplaces rushing you to pay outside the platform", "Cashback or reward messages with payment links"],
        "prevention_tips": ["Remember: you NEVER need a PIN or QR scan to receive money", "Reject collect requests from unknown users", "Verify customer care numbers only from official apps/websites", "Set a daily UPI transaction limit", "Use app lock on payment apps"],
        "real_example": "A man selling furniture online was contacted by a 'buyer' who sent a QR code saying 'scan this to receive the advance payment'. He scanned it and entered his PIN — instantly sending $600 to the scammer instead of receiving anything."
    },
    {
        "slug": "fake-job-scams",
        "title": "Fake Job Scams",
        "icon": "Briefcase",
        "severity": "high",
        "description": "Fraudsters post fake job listings or send unsolicited offers with attractive salaries, then demand 'registration fees', 'training deposits', or steal personal documents.",
        "how_it_works": "You receive a WhatsApp/Telegram message or email offering a work-from-home job with high pay for simple tasks. After a fake 'interview', you're asked to pay a security deposit, buy a starter kit, or complete paid 'tasks' where early small payouts build trust before a large final 'investment' disappears.",
        "warning_signs": ["Job offers you never applied for", "Guaranteed high income for trivial work (liking videos, rating products)", "Any request for upfront payment or deposits", "Interviews conducted entirely on Telegram/WhatsApp", "Company email addresses using Gmail/Yahoo domains"],
        "prevention_tips": ["Legitimate employers never charge candidates money", "Verify the company on LinkedIn and its official website", "Check the recruiter's email domain matches the company", "Never share Aadhaar/SSN/passport scans with unverified recruiters", "Search '[company name] + scam' before engaging"],
        "real_example": "A graduate received a Telegram message offering $50/day for reviewing hotels online. After earning $30 in 'commissions', she was told to unlock higher-paying tasks with a $500 deposit, then $2,000 more to 'withdraw earnings'. The group vanished overnight with her $2,500."
    },
    {
        "slug": "lottery-scams",
        "title": "Lottery & Prize Scams",
        "icon": "Gift",
        "severity": "high",
        "description": "You're told you've won a lottery, lucky draw, or prize you never entered — but must pay 'taxes', 'processing fees', or 'customs charges' to claim it.",
        "how_it_works": "Scammers send emails, SMS, or WhatsApp messages announcing you've won a huge prize (often using real brand names like KBC, Coca-Cola, or Google). To claim it, you must first pay fees or share bank details. Each payment leads to another 'required' fee until the victim realizes there is no prize.",
        "warning_signs": ["Winning a lottery you never entered", "Requests for advance fees to release winnings", "Messages full of spelling errors and urgency", "Use of famous brand names and fake certificates", "Communication only via WhatsApp or personal email"],
        "prevention_tips": ["Real lotteries never ask winners to pay fees upfront", "Never share bank details to 'receive' prize money", "Ignore and block prize messages from unknown numbers", "Check official brand websites for genuine contests", "Report lottery scam messages to cybercrime portals"],
        "real_example": "A farmer received a call saying he'd won a $35,000 TV show lottery. Over 3 months he paid $4,000 in 'GST', 'RBI clearance', and 'insurance' fees, borrowing from relatives. The 'lottery office' number was switched off after the final payment."
    },
    {
        "slug": "investment-scams",
        "title": "Investment & Crypto Scams",
        "icon": "TrendingUp",
        "severity": "critical",
        "description": "Fraudulent schemes promising guaranteed high returns via stocks, forex, or cryptocurrency. Includes Ponzi schemes, pump-and-dump groups, and fake trading platforms.",
        "how_it_works": "Scammers build trust through social media, dating apps, or Telegram 'trading groups' showing fake profit screenshots. Victims invest small amounts and see fake 'profits' on a fraudulent dashboard, encouraging bigger deposits. Withdrawals are blocked with excuses (taxes, fees) until the platform disappears — a technique called 'pig butchering'.",
        "warning_signs": ["Guaranteed returns (e.g., 'double your money in 30 days')", "Pressure to invest quickly before an 'opportunity' closes", "Unregistered platforms or apps shared via APK links", "Strangers on social/dating apps offering trading tips", "Withdrawal requires paying extra 'taxes' or 'fees'"],
        "prevention_tips": ["If returns sound too good to be true, they are", "Verify platforms with financial regulators (SEC/SEBI/FCA)", "Never install trading apps from links — use official stores", "Never let anyone 'manage' your trading account", "Start assumption: unsolicited investment advice = scam"],
        "real_example": "An IT professional met someone on a dating app who introduced him to a crypto platform showing 20% monthly returns. He invested $45,000 over 4 months. When he tried withdrawing, the site demanded a 15% 'tax'. After paying, the site and his 'friend' both vanished."
    },
    {
        "slug": "tech-support-scams",
        "title": "Tech Support Scams",
        "icon": "MonitorX",
        "severity": "high",
        "description": "Fake pop-ups, calls, or emails claim your computer is infected, then charge you for useless 'repairs' or install malware to steal banking data.",
        "how_it_works": "A scary pop-up appears saying 'Your PC is infected — call Microsoft support now', or you get a cold call from 'Windows technical department'. The scammer asks you to install remote access software (AnyDesk, TeamViewer), fakes a virus scan, charges hundreds for 'fixing' it, and may quietly steal saved passwords and banking sessions.",
        "warning_signs": ["Pop-ups with alarm sounds and support phone numbers", "Cold calls claiming to be Microsoft/Apple/Google", "Requests to install remote access software", "Payment demanded via gift cards or crypto", "Claims that your IP address is 'compromised'"],
        "prevention_tips": ["Microsoft/Apple never call you or show phone numbers in alerts", "Close scary pop-ups with Task Manager; never call the number", "Never give strangers remote access to your device", "Use a reputable antivirus and keep it updated", "Never pay for support with gift cards"],
        "real_example": "An elderly woman saw a full-screen alert saying her computer was hacked. She called the number, allowed remote access, and watched a fake 'scan'. The scammer charged $900 for cleanup and silently transferred $8,000 from her logged-in bank session."
    },
    {
        "slug": "social-media-scams",
        "title": "Social Media Scams",
        "icon": "Users",
        "severity": "high",
        "description": "Scams spread through Instagram, Facebook, WhatsApp, and X — including hacked friend accounts asking for money, fake giveaways, romance scams, and impersonation.",
        "how_it_works": "Scammers hack or clone a friend's profile and message you with an emergency: 'I'm stuck, please send money urgently'. Others run fake celebrity giveaways, romance scams building emotional bonds before requesting money, or 'influencer' investment promotions. Verification is skipped because the message comes from a 'trusted' face.",
        "warning_signs": ["Friends suddenly asking for money via chat", "Giveaways requiring a 'small fee' or your card details", "New online romantic interest who can never video call", "Profiles with few posts but model-quality photos", "Links promising to show 'who viewed your profile'"],
        "prevention_tips": ["Verify money requests by calling the friend directly", "Enable 2FA on all social accounts", "Keep profiles private and audit friend lists", "Reverse-image search suspicious profile photos", "Never send money or gift cards to online-only contacts"],
        "real_example": "A student got a WhatsApp message from her 'uncle' (cloned profile with his photo) asking for $400 for a hospital emergency, promising to repay that evening. She paid instantly. The real uncle knew nothing — his profile photo had been copied from Facebook."
    },
    {
        "slug": "fake-shopping-websites",
        "title": "Fake Shopping Websites",
        "icon": "ShoppingCart",
        "severity": "high",
        "description": "Fraudulent online stores offer branded products at unbelievable discounts, take your payment, and either ship nothing, ship counterfeits, or steal your card details.",
        "how_it_works": "Scammers run social media ads with 80-90% discounts on popular brands, leading to professional-looking stores built in hours. They accept only prepaid payments (no cash on delivery). After payment, the product never arrives, tracking numbers are fake, and 'customer support' stops responding. Card details entered may be reused for fraud.",
        "warning_signs": ["Discounts too massive to be real (iPhone at 85% off)", "Website created recently (check domain age)", "No cash-on-delivery option, prepaid only", "No physical address, working phone, or return policy", "Slightly misspelled brand domains (amaz0n-deals.shop)"],
        "prevention_tips": ["Buy from official brand sites or established marketplaces", "Check domain age at who.is — new domains are red flags", "Look for verified reviews outside the site itself", "Prefer cash on delivery for unknown sellers", "Use virtual/disposable cards for online shopping"],
        "real_example": "During a festive sale, a fake website cloned a famous fashion brand offering 90% off. Over 5,000 shoppers paid online. The site closed in two weeks; buyers received nothing, and many later reported unauthorized charges on the same cards."
    },
    {
        "slug": "qr-code-scams",
        "title": "QR Code Scams",
        "icon": "QrCode",
        "severity": "high",
        "description": "Malicious QR codes redirect you to phishing sites, trigger payments you didn't intend, or install malware — exploiting the fact that you can't read a QR code with your eyes.",
        "how_it_works": "Scammers place fake QR stickers over real ones (parking meters, restaurant menus, payment counters) or send QR codes claiming you'll receive money. Scanning leads to fake payment pages, phishing login screens, or automatic app downloads. In payment scams, victims are tricked into approving outgoing transfers.",
        "warning_signs": ["QR codes sent by strangers to 'receive' money", "Stickers pasted over original QR codes in public", "Scanned QR opens an unexpected login or payment page", "URLs shown after scan are shortened or misspelled", "QR codes in unsolicited emails or parcels"],
        "prevention_tips": ["Scanning to RECEIVE money is always a scam — receiving needs no scan", "Preview the URL after scanning before opening", "Check for tampered stickers on public QR codes", "Use payment apps' built-in scanner, which flags suspicious codes", "Never enter credentials on pages opened from random QRs"],
        "real_example": "Drivers in several cities scanned QR stickers on parking meters that scammers had pasted over official ones. The fake page collected card details for 'parking payment'. Hundreds of cards were compromised before the stickers were discovered."
    },
    {
        "slug": "sim-swap-fraud",
        "title": "SIM Swap Fraud",
        "icon": "CreditCard",
        "severity": "critical",
        "description": "Criminals hijack your mobile number by getting a duplicate SIM issued, then intercept your OTPs to empty bank accounts and take over your digital identity.",
        "how_it_works": "Using personal data harvested from phishing or leaks, the scammer convinces your telecom operator to issue a replacement SIM ('lost phone'), or tricks you into approving an eSIM transfer. Your phone suddenly loses signal. During those hours, every OTP for your bank, email, and wallets goes to the scammer.",
        "warning_signs": ["Sudden, unexplained loss of mobile network for hours", "SMS about SIM change/eSIM activation you didn't request", "Multiple calls from strangers trying to keep you on the line", "Alerts about password resets you didn't initiate", "Being asked to forward an SMS or dial unknown codes"],
        "prevention_tips": ["Set a SIM lock PIN and a porting password with your telecom", "If signal dies unexpectedly, contact your operator immediately", "Use authenticator apps instead of SMS OTP where possible", "Never share Aadhaar/ID scans with unverified parties", "Monitor bank alerts on email as backup to SMS"],
        "real_example": "A businessman's phone went dead at 11 PM. By 6 AM, scammers using a duplicate SIM had reset his banking passwords via OTP and moved $28,000 through 14 transfers. The duplicate SIM was issued using a forged ID at a small retail outlet."
    }
]

SAFETY_TIPS = [
    {"slug": "strong-passwords", "title": "Strong Password Practices", "icon": "Lock", "category": "Accounts",
     "summary": "Your password is the front door to your digital life. Weak or reused passwords cause the majority of account takeovers.",
     "points": ["Use at least 12-16 characters mixing letters, numbers, and symbols", "Never reuse passwords across sites — one breach exposes all", "Use a password manager (Bitwarden, 1Password) to generate and store them", "Prefer passphrases: 'purple-tiger-eats-42-mangoes' beats 'P@ss123'", "Change passwords immediately after any breach notification"]},
    {"slug": "two-factor-authentication", "title": "Two-Factor Authentication (2FA)", "icon": "ShieldCheck", "category": "Accounts",
     "summary": "2FA adds a second lock. Even if your password leaks, attackers can't get in without the second factor.",
     "points": ["Enable 2FA on email, banking, and social media first", "Prefer authenticator apps (Google Authenticator, Authy) over SMS", "Hardware keys (YubiKey) offer the strongest protection", "Save backup codes somewhere safe and offline", "Never share 2FA codes — no legitimate service asks for them"]},
    {"slug": "safe-browsing", "title": "Safe Browsing Habits", "icon": "Globe", "category": "Web",
     "summary": "Most malware and phishing attacks start in your browser. Smart habits block them before they start.",
     "points": ["Check for HTTPS and the correct domain before entering data", "Don't click ads promising prizes, downloads, or shocking news", "Keep your browser updated — updates patch security holes", "Use an ad/tracker blocker like uBlock Origin", "Type important URLs (bank, email) manually or use bookmarks"]},
    {"slug": "email-security", "title": "Email Security", "icon": "Mail", "category": "Communication",
     "summary": "Email is the #1 attack channel. Treat every unexpected message with healthy suspicion.",
     "points": ["Verify sender addresses carefully — look for misspellings", "Never open attachments you weren't expecting", "Hover over links to preview the real destination", "Use a separate email for banking vs. sign-ups", "Enable spam filtering and report phishing emails"]},
    {"slug": "mobile-security", "title": "Mobile Security", "icon": "Smartphone", "category": "Devices",
     "summary": "Your phone holds your money, identity, and memories. Secure it like a vault.",
     "points": ["Install apps only from official stores — never from APK links", "Review app permissions; deny access that isn't needed", "Keep your OS updated and enable automatic updates", "Use biometric lock + strong PIN, and enable Find My Device", "Never leave your phone unlocked and unattended"]},
    {"slug": "banking-safety", "title": "Online Banking Safety", "icon": "Landmark", "category": "Finance",
     "summary": "Banking fraud is devastating and fast. A few habits make you a very hard target.",
     "points": ["Never share OTP, PIN, CVV, or passwords — banks never ask", "Use the official banking app, not links from SMS/email", "Set transaction limits and enable instant alerts", "Avoid banking on public Wi-Fi or shared computers", "Check statements weekly for unfamiliar transactions"]},
    {"slug": "social-media-privacy", "title": "Social Media Privacy", "icon": "UserCog", "category": "Social",
     "summary": "Oversharing feeds scammers the exact data they need to impersonate or target you.",
     "points": ["Set profiles to private and audit followers regularly", "Don't post travel plans, IDs, tickets, or financial info", "Disable location tagging on posts", "Be skeptical of friend requests from strangers or duplicates", "Review third-party app access to your accounts yearly"]},
    {"slug": "public-wifi-safety", "title": "Public Wi-Fi Safety", "icon": "Wifi", "category": "Network",
     "summary": "Free Wi-Fi can cost you everything. Open networks let attackers intercept your traffic.",
     "points": ["Avoid banking or shopping on public Wi-Fi", "Use a reputable VPN when on open networks", "Turn off auto-connect to open Wi-Fi networks", "Prefer your mobile hotspot for sensitive tasks", "Forget public networks after use"]},
    {"slug": "software-updates", "title": "Software Updates", "icon": "RefreshCw", "category": "Devices",
     "summary": "Updates aren't just features — they patch security holes attackers actively exploit.",
     "points": ["Enable automatic updates on OS, browser, and apps", "Update routers and IoT devices — they're often forgotten", "Uninstall software you no longer use", "Don't ignore update prompts for weeks", "Only download updates from official sources"]},
    {"slug": "data-backup", "title": "Data Backup", "icon": "DatabaseBackup", "category": "Data",
     "summary": "Ransomware and device loss can wipe your digital life. Backups are your insurance.",
     "points": ["Follow 3-2-1: 3 copies, 2 media types, 1 offsite/cloud", "Automate backups — manual ones get forgotten", "Test restores twice a year", "Encrypt sensitive backups", "Keep one backup disconnected to survive ransomware"]}
]

QUIZ_QUESTIONS = [
    {"question": "A caller claiming to be from your bank asks for the OTP sent to your phone to 'cancel a fraudulent transaction'. What should you do?",
     "options": ["Share the OTP quickly to stop the fraud", "Hang up and call the bank's official number yourself", "Ask the caller to verify their employee ID first", "Share only half the OTP as a test"],
     "correct_index": 1, "explanation": "Banks NEVER ask for OTPs. Sharing any part of it lets scammers authorize transactions. Always hang up and call the official number printed on your card."},
    {"question": "Which of these passwords is the strongest?",
     "options": ["Password@123", "john1990", "orbit-mango-73-Lantern!", "qwerty!@#"],
     "correct_index": 2, "explanation": "Long passphrases with unrelated words, numbers, and symbols are far harder to crack than short patterns or personal info."},
    {"question": "You receive a QR code from a buyer who says 'scan this to receive your payment'. What's the truth?",
     "options": ["Scanning it will credit money to your account", "You need to enter your PIN to receive the money", "Receiving money NEVER requires scanning a QR or entering a PIN", "It's safe if the amount shown is correct"],
     "correct_index": 2, "explanation": "QR scans and PINs are only needed to SEND money. Anyone telling you otherwise is trying to steal from you."},
    {"question": "An email from 'support@amaz0n-orders.com' says your account is locked. What's the biggest red flag?",
     "options": ["The email mentions your account", "The misspelled domain 'amaz0n'", "It arrived in the morning", "It has the Amazon logo"],
     "correct_index": 1, "explanation": "Scammers use lookalike domains with swapped characters (0 for o). Always check the sender's exact domain — logos are easy to copy."},
    {"question": "What is 'two-factor authentication' (2FA)?",
     "options": ["Using two passwords for one account", "A second verification step (like an app code) after your password", "Logging in from two devices", "Changing your password twice a year"],
     "correct_index": 1, "explanation": "2FA combines something you know (password) with something you have (phone/app code), blocking attackers who steal just your password."},
    {"question": "A work-from-home job offer promises $50/day for liking videos but asks for a $100 'registration deposit'. This is:",
     "options": ["A standard hiring practice", "Legitimate if the company has a website", "A fake job scam — real employers never charge candidates", "Safe if you pay via UPI"],
     "correct_index": 2, "explanation": "Any job demanding upfront payment is a scam. Legitimate employers pay YOU, never the reverse."},
    {"question": "Your phone suddenly loses network signal for several hours for no reason. This could be a sign of:",
     "options": ["A phone battery issue", "SIM swap fraud — call your operator immediately", "Normal network maintenance, ignore it", "Your phone needs a restart"],
     "correct_index": 1, "explanation": "Unexpected signal loss can mean a scammer activated a duplicate SIM to intercept your OTPs. Contact your operator immediately and alert your bank."},
    {"question": "Which is the safest way to access your bank's website?",
     "options": ["Clicking a link in an SMS from the bank", "Searching Google and clicking the first result", "Typing the official URL manually or using the official app", "Using a link a friend shared on WhatsApp"],
     "correct_index": 2, "explanation": "SMS links and even search ads can be spoofed. Manually typing the URL or using the official app avoids phishing clones."},
    {"question": "A pop-up says 'Your PC is infected! Call Microsoft Support: 1-800-XXX' with a loud alarm. What should you do?",
     "options": ["Call the number immediately", "Close the browser via Task Manager and never call the number", "Pay for the cleanup service offered", "Install the remote support tool it suggests"],
     "correct_index": 1, "explanation": "Microsoft never displays phone numbers in alerts or calls users. These pop-ups are tech support scams — close them and run your own antivirus scan."},
    {"question": "On public Wi-Fi at a cafe, which activity is riskiest?",
     "options": ["Reading news articles", "Watching YouTube", "Logging into your bank account", "Checking the weather"],
     "correct_index": 2, "explanation": "Open networks can be intercepted. Never do banking or enter passwords on public Wi-Fi without a VPN."},
    {"question": "A new online friend you've never video-called asks you to invest in a crypto platform showing 20% monthly returns. This pattern is called:",
     "options": ["Angel investing", "Pig butchering scam", "Day trading", "Crowdfunding"],
     "correct_index": 1, "explanation": "'Pig butchering' scams build trust over weeks, show fake profits on fraudulent platforms, then vanish with your money. Guaranteed high returns don't exist."},
    {"question": "What does HTTPS with a padlock icon in the address bar guarantee?",
     "options": ["The website is 100% legitimate and safe", "Your connection to the site is encrypted — but the site itself can still be a scam", "The website has no viruses", "The site is government approved"],
     "correct_index": 1, "explanation": "HTTPS only encrypts traffic. Scammers can get HTTPS certificates for fake sites too — always verify the domain name."},
    {"question": "You get a WhatsApp message from your cousin's number asking for urgent money for an accident. Best first step?",
     "options": ["Send money immediately — it's an emergency", "Call your cousin directly on their number to verify", "Ask for the hospital name over chat", "Forward the message to family"],
     "correct_index": 1, "explanation": "Scammers clone or hijack accounts and exploit urgency. A direct phone call verifies the truth in seconds."},
    {"question": "Which backup strategy best protects you from ransomware?",
     "options": ["One copy on the same computer", "Copies on two folders of the same drive", "3-2-1 rule with one backup kept offline/disconnected", "Emailing files to yourself"],
     "correct_index": 2, "explanation": "Ransomware encrypts everything connected. An offline backup copy survives and lets you recover without paying."},
    {"question": "'You've won $50,000 in a lottery! Pay $200 processing fee to claim.' You never entered any lottery. This is:",
     "options": ["A lucky day — pay the small fee", "Real if they show a certificate", "An advance-fee lottery scam", "Worth negotiating a lower fee"],
     "correct_index": 2, "explanation": "You can't win a lottery you never entered, and real prizes never require upfront fees. Each payment leads to more fee demands."}
]

BLOG_POSTS = [
    {"slug": "ai-voice-cloning-scams-rise", "title": "AI Voice Cloning Scams Are Exploding: How to Protect Your Family",
     "excerpt": "Scammers now need just 3 seconds of audio to clone a voice. 'Family emergency' calls have never been more convincing — here's your defense plan.",
     "author": "SafeNet Team", "category": "AI Threats", "read_time": "5 min",
     "image": "https://images.unsplash.com/photo-1729554608003-5ec8be42da1d?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
     "content": "Voice cloning technology has crossed a dangerous threshold. With just a few seconds of audio scraped from social media videos, scammers can generate a convincing replica of anyone's voice.\n\nThe scam usually plays out as a panicked call: a 'grandchild' arrested abroad, a 'daughter' in a hospital, a 'son' kidnapped. The voice sounds real because, in a sense, it is — an AI model trained on the real person's speech.\n\nHow to defend your family:\n\n1. Create a family code word. Agree on a secret word that must be spoken in any emergency money request. AI can clone a voice, but it can't know your secret.\n\n2. Verify through a second channel. Hang up and call the person's real number. Scammers rely on you staying on the line in panic mode.\n\n3. Slow down. Urgency is the weapon. Any legitimate emergency survives a 5-minute verification.\n\n4. Limit public voice content. Consider making videos featuring your voice private, especially for elderly family members' protection.\n\n5. Educate the most vulnerable. Grandparents are prime targets. Walk them through this exact scenario before it happens.\n\nIf you're targeted, report the incident to your national cybercrime portal immediately and warn your family network — scammers often re-target the same families."},
    {"slug": "upi-fraud-2026-trends", "title": "UPI Fraud in 2026: The 7 Newest Tricks Emptying Bank Accounts",
     "excerpt": "From fake 'collect requests' to malicious screen-share apps, UPI scams have evolved. Know the latest playbook scammers are using this year.",
     "author": "SafeNet Team", "category": "Payment Fraud", "read_time": "6 min",
     "image": "https://images.unsplash.com/photo-1614064548237-096f735f344f?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
     "content": "Instant payments mean instant theft when things go wrong. Here are the top UPI fraud patterns we're tracking in 2026:\n\n1. The reversed QR trick. Scammers on marketplaces send QR codes claiming they're for 'receiving payment'. Scanning + PIN = money gone. Remember: receiving money never needs a scan or PIN.\n\n2. Fake customer care numbers. Fraudsters buy ads and edit business listings so their number appears when you search 'PhonePe support'. They then walk you through 'verification transfers'.\n\n3. Screen-share hijacking. Posing as support, scammers ask you to install AnyDesk or similar. Once they see your screen, they capture PINs and OTPs in real time.\n\n4. The accidental transfer. You receive money 'by mistake' and an emotional request to return it. The original transfer was made with a stolen card — when it's reversed, you lose the amount you 'returned'.\n\n5. Collect request flooding. Multiple payment requests disguised with names like 'REFUND-PROCESS'. Approving one with your PIN sends money out.\n\n6. Fake payment screenshots. Sellers get doctored 'payment successful' images. Always verify money in your own app before handing over goods.\n\n7. Malicious APKs. 'Special offer' apps sent via WhatsApp that read your SMS and forward OTPs silently.\n\nGolden rules: never approve requests you didn't initiate, never install apps from links, and treat every 'support' number you didn't get from the official app as hostile."},
    {"slug": "password-manager-guide", "title": "Why You Need a Password Manager (And How to Start in 10 Minutes)",
     "excerpt": "Reusing one password across sites is like using one key for your house, car, and office. Here's the painless way to fix it today.",
     "author": "SafeNet Team", "category": "Security Basics", "read_time": "4 min",
     "image": "https://images.unsplash.com/photo-1728756666032-d0b5552b6384?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
     "content": "The average person has 100+ online accounts but remembers about 5 passwords. The math forces reuse — and reuse is how one leaked database becomes a takeover of your entire digital life.\n\nA password manager solves this by remembering hundreds of unique, random passwords behind one strong master password.\n\nGetting started in 10 minutes:\n\n1. Choose a manager (2 min). Bitwarden (free, open source), 1Password, or Proton Pass are all excellent. Avoid storing passwords in browser notes or spreadsheets.\n\n2. Create your master passphrase (3 min). Four random words + a number: 'coral-thunder-biscuit-91'. This is the ONE password you memorize. Make it long, make it unique.\n\n3. Install the app + browser extension (2 min). The extension auto-fills logins and catches phishing sites — it won't fill your password on a fake domain, which is a hidden superpower.\n\n4. Secure your top 5 accounts (3 min). Email first (it resets everything else), then banking, then social media. Let the manager generate 20-character random passwords.\n\n5. Enable 2FA on the manager itself. Your vault deserves a second lock.\n\nFrom there, update other passwords gradually as you log into sites. Within a month, you'll be more secure than 95% of internet users."},
    {"slug": "how-to-spot-phishing-2026", "title": "The 10-Second Phishing Check: Spot Fake Emails Like a Pro",
     "excerpt": "Phishing causes over 90% of data breaches. This simple 4-step check takes 10 seconds and catches nearly all of them.",
     "author": "SafeNet Team", "category": "Phishing", "read_time": "4 min",
     "image": "https://images.unsplash.com/photo-1750969185331-e03829f72c7d?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
     "content": "You don't need to be a security expert to beat phishing. You need a 10-second habit. Before acting on any email that asks you to click, download, or pay, run this check:\n\n1. SENDER (3 seconds). Look at the actual email address, not the display name. 'PayPal Support <security@paypa1-alerts.com>' is a scam. Watch for swapped letters, extra words, and free email domains for 'official' business.\n\n2. URGENCY (2 seconds). 'Account suspended in 24 hours.' 'Immediate action required.' 'Final warning.' Legitimate companies rarely threaten; scammers always do. Urgency is designed to bypass your thinking.\n\n3. LINKS (3 seconds). Hover (don't click) over links. Does the URL match the official domain exactly? 'microsoft-verify.support.net' is NOT microsoft.com. On mobile, long-press to preview.\n\n4. ASK (2 seconds). Is this expected? Did you order this package, enter this lottery, request this reset? Unexpected = suspicious by default.\n\nIf anything fails the check: don't click. Go to the official website directly by typing the address, or contact the company through channels you find yourself.\n\nBonus tell-tales: generic greetings ('Dear Customer'), attachment types like .html or .zip, requests for OTPs or passwords (never legitimate), and reply addresses that differ from sender addresses.\n\nShare this check with the least tech-savvy person you know — it might be the most valuable 10 seconds of their year."},
    {"slug": "protect-elderly-parents-online", "title": "A Practical Guide to Protecting Elderly Parents from Online Scams",
     "excerpt": "Adults over 60 lose more money to scams than any other group. These 8 practical steps dramatically lower the risk for your loved ones.",
     "author": "SafeNet Team", "category": "Family Safety", "read_time": "6 min",
     "image": "https://images.unsplash.com/photo-1614064548237-096f735f344f?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
     "content": "Scammers deliberately target older adults: they're often more trusting, less familiar with digital tricks, and have savings worth stealing. Protecting parents isn't about taking away their independence — it's about building guardrails together.\n\n1. Have the talk without judgment. Share news stories, not lectures. 'This happened to someone's dad — how would we handle it?' works better than warnings.\n\n2. Create a family code word for emergencies. Any call requesting money must include it. This single step defeats voice cloning and 'grandchild in trouble' scams.\n\n3. Set up their devices defensively. Enable auto-updates, install a reputable antivirus, turn on call filtering/spam detection, and set app store installs to require a password.\n\n4. Harden their bank accounts. Lower daily transfer limits, enable alerts to YOUR phone too (with their consent), and register their numbers on do-not-call lists.\n\n5. Establish the golden rule: never act on inbound calls. Whoever calls claiming to be the bank, police, or tech support — hang up, and call back on an official number.\n\n6. Make yourself the checkpoint. 'Before paying anyone new or sharing any code, call me first — no matter what.' Remove the shame from asking.\n\n7. Watch for warning signs. Secretive phone calls, sudden gift card purchases, wire transfers, or new 'online friends' asking for help.\n\n8. If they do get scammed: react with support, not blame. Report to the cybercrime portal and bank immediately — speed matters for freezing transfers. Victims who feel ashamed hide repeat scams; victims who feel supported report them."}
]
